
- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: python setup
  include_role:
    name: common
    tasks_from: python


- name: service setup
  include_role:
    name: common
    tasks_from: systemd.yaml
