- name: Install mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: install boto3 and botocore
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - boto3
  - botocore

- name: We need to change the default root password in order to start using the database service
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1