  - name: ccreate roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true 
      home: /app

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory

  - name: "Downloadinf {{ coponent }} zip file"
    ansible.builtin.get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/{{ coponent }}-v3.zip"
      dest: "/tmp/{{ coponent }}.zip"

   # this module thinks file exist on ansible control server, needs to extract on to remote machine
  # remote_src: yes means files already exist in catalogue server
  - name: "Unarchive a {{ coponent }} file"
    ansible.builtin.unarchive:
      src: "/tmp/{{ coponent }}.zip"
      dest: /app
      remote_src: yes