- name: "copy {{ component }}.service file"
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"
  
- name: "{{ component }} system deamon reload"
  ansible.builtin.systemd_service:
    daemon_reload:  true

- name: "Start service {{ component }}"
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted # even app is not running we can restart
    enabled: yes
