- name: nodesetup setup
  include_role:
  - name: common
    tasks_from: nodejs

- name: app setup
  include_role:
  - name: common
    tasks_from: app-setup

- name: service setup
  include_role:
  - name: common
    tasks_from: systemd.yaml

